services:
  db_go:
    container_name: db_go
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: newpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: user_crud_api
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}